version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.5.1
    ports:
    - "9200:9200"
    - "9300:9300"
  kibana:
    image: kibana:6.5.1
    ports:
    - "5601:5601"
    links:
    - elasticsearch